### ISSUE TITLE
[Feature]: Possibility to stop cleaning nodes in finish of work.

### ISSUE THREAD

**Issue by loguntsov** [satori-com/mzbench#125]
It can be helpful for debug. I forced to change sources right now there: https://github.com/machinezone/mzbench/blob/master/server/src/mzb_api_bench.erl#L396
to disable this line.
Can we have some options in config for this case ?

**Comment by timofey-barmin** [comment]
Try setting variable deallocate_after_bench=false. If this option is set to false the system will not deallocate the instances in your cloud and won't do node cleaning as well. It is for debug purposes only. When you finished with the debugging nodes could be cleaned and deallocated using "mzbench [--host=<host>] deallocate_cluster <cluster_id>" command. Cluster id could be obtained using command "mzbench [--host=<host>] clusters_info". Feel free to reopen the issue if it doesn't work for you.
