### ISSUE TITLE
Fatal error when running start_server

### ISSUE THREAD

**Issue by joboscribe** [satori-com/mzbench#132]
I pulled commit d1ac73ff771c8b85caac356ea45886e5505e9a1e, i'm running on Ubuntu 16.04.4 LTS, Erlang OTP Release 20, GCC 5.4.0.

When i run `bin/mzbench start_server` i see https://gist.github.com/joboscribe/ee0827849bbb7dff1c89cb9d52bcee43.  

Let me know if you'd like any more information.

**Comment by parsifal-47** [comment]
Thanks for reporting this, it looks like you need `zlib` to compile `hdrhistogram` dependency, on Ubuntu you need to run something like `sudo apt-get install zlib1g-dev`

Sorry for that, it should be specified in our docs, please try again with `zlib` installed and let me know if you have any issues

**Comment by joboscribe** [comment]
That seems to have cleared it up:
```
$ ./bin/mzbench start_server
Executing make -C /root/mzbench/bin/../server generate
.........................
Waiting for server application start
.Webserver is started at http://127.0.0.1:4800
No config file is used, to create one run:
cp ~/.config/mzbench/server.config.example ~/.config/mzbench/server.config
ok
```

I'll close this issue. Thank you for the help.
