### ISSUE TITLE
Can't run scenario with pool of more than 994 workers

### ISSUE THREAD

**Issue by joboscribe** [satori-com/mzbench#133]
I've tried running a scenario several times now and found that it runs if there are 995 workers but fails if there are 996. 

```
#!benchDL


#######
# Scenario:
# A single subscriber reading from "prefix/clients/#" topic filter
# 1k publisher publishing to exclusive topic "prefix/clients/{client_id}"
# Overall msg rate: 1k msg/s
# Message size: 150 random bytes
# Running time: 5 min
#######

make_install(git = "https://github.com/erlio/vmq_mzbench.git",
             branch = "master")

pool(size = 1,
     worker_type = mqtt_worker):

            connect([t(host, "[server name]"),
                    t(port,1883),
                    t(client,"subscriber1"),
                    t(clean_session,true),
                    t(keepalive_interval,60),
                    t(proto_version,4), t(reconnect_timeout,4)
                    ])

            wait(1 sec)
            subscribe("prefix/clients/#", 0)


pool(size = 994,
     worker_type = mqtt_worker,
     worker_start = poisson(994 rps)):

            connect([t(host, "[server name]"),
                    t(port,1883),
                    t(client,fixed_client_id("pool1", worker_id())),
                    t(clean_session,true),
                    t(keepalive_interval,60),
                    t(proto_version,4), t(reconnect_timeout,4)
                    ])

            wait(10 sec)
            set_signal("connect1",1)
            wait_signal("connect1", 994)
            loop(time = 1 min, rate = 1 rps):
                publish_to_self("prefix/clients/", random_binary(150), 0)
            disconnect()
```

If i increase the second pool size, poisson rate and wait_signal count to 995 i see `995 of 996 workers failed` as the reason for failure.

Looking through the logs didn't help me much but here they are:
user logs: https://gist.github.com/joboscribe/30cefdc70489cf100a96797fb4836624
system logs: https://gist.github.com/joboscribe/c6e07e7add581abb8def77d7225baa46

I'm running all of this on an AWS EC2 t2.micro, so i'm open to the idea that it's a resource issue, but while running the only thing that appears to be a limiting factor is CPU, the memory barely moves. 

Also, i've tried running two pools of publishers, one with 994 workers and another with 100 and that works fine. I could try running more variations on this same theme but i have other stuff i'm supposed to be working on, sadly.

Let me know if any other information would be helpful, like server config or anything else.

**Comment by parsifal-47** [comment]
It looks like you running out of file descriptors, you need to increase this limit at your instances,
the following guide may be helpful:
https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by joboscribe** [comment]
Thanks for the prompt reply. 

I increased the file descriptor limit from 99,287 to 1,000,000:
```
root@ip-something:~/mzbench# cat /proc/sys/fs/file-max
99287
root@ip-something:~/mzbench# sysctl -w fs.file-max=1000000
fs.file-max = 1000000
root@ip-something:~/mzbench# cat /proc/sys/fs/file-max
1000000
```
I still see what looks to me like the same stream of errors. Is there a compiler flag or something similar that i might need to change?

**Comment by parsifal-47** [comment]
shouldn't be, it might be that you have some additional limits for the user,
I'll find out how to check that these limits are updated for your process

**Comment by joboscribe** [comment]
I've updated the file limits for the root user (which is what i'm using for this early phase) and that fixed it. 

Sorry for the erroneous issue and thank you for the help.

**Comment by parsifal-47** [comment]
no worries, feel free to reach out with any further issues!
