### ISSUE TITLE
The way to export/import benchmark results

### ISSUE THREAD

**Issue by eckucukoglu** [satori-com/mzbench#136]
Hi,

Regarding presenting the benchmark results, Is there a way to import and export the benchmark results for later viewings? 

My aim to ask that is almost same with #135, however I guess developing report functionality could be future work. Just exporting results (database dumb?, file storing, ...) would work for me right now. Since I do not know the internal implementation details, I could not handle that.

Thank you.

**Comment by parsifal-47** [comment]
Hi,
thanks for asking, it is possible from dashboard and cli

from dashboard:
<img width="369" alt="screen shot 2018-03-20 at 12 21 32 pm" src="https://user-images.githubusercontent.com/4032256/37651732-6e9e18e0-2c39-11e8-8b28-c06812a0171b.png">

from cli:
```
mzbench [--host=<host>] [--no_cert_check] data [(--target=<name>...)] [--format=(csv|json)] <bench_id>
```

please let me know if you have questions,
thank you!

**Comment by eckucukoglu** [comment]
Nice, it is good to have data report as a file.
Do we have a chance to import the downloaded data files to mzbench, to see graphs?

Thank you.

**Comment by parsifal-47** [comment]
That's interesting idea,
currently, we don't have any charts that are separated from benchmarks,
all charts are related to some execution,
I see how we could implement import/export of the entire benchmarks but importing a chart should somehow change entity relations

what is your idea about it? do you want to see separated list of charts or you see import as a replacement for some of the existing charts inside a benchmark?

**Comment by eckucukoglu** [comment]
No, not as a replacement. Idea behind my request is that the charts (with scenario details) are valuable for me. I do not want to lose them, because I will compare different broker solutions with different specs. So, I'm expecting from a complete export/import functionality to recover every benchmarks with its full content (scenarios, names, tags, etc...)

**Comment by parsifal-47** [comment]
we had the same idea, but we just kept all benchmarks and added backups to make sure nothing is lost, but we had stateful server. 
As far as I understand, in your case server is deployed on demand

**Comment by eckucukoglu** [comment]
How did you keep all benchmarks? Could you restore them later? Yes, my mzbench server is deployed on-demand.

Thank you.

**Comment by parsifal-47** [comment]
All benchmarks are located in `bench_data_dir` set with config, by default it is `~/.local/share/mzbench_api/data`, if you just copy this folder, you'll have all the data

**Comment by eckucukoglu** [comment]
This is exactly what I need. Thank you very much.
