### ISSUE TITLE
How to add additional functionalities to the existing worker

### ISSUE THREAD

**Issue by protostartup** [satori-com/mzbench#153]
Hi,

I added few additional functions to the existing mqtt_worker, but am not able to run it.

I guess the problem is with "make_install" syntax am not able to fully get it.

Am attaching the error log here, Some help is really appreciated.

07:00:35.705 [error] [ API ] <0.498.0> [ REMOTE EXEC ] Command execution failed:
Cmd: bash -c -l "export PATH='/home/trioka/cluster_test/mzbench/mzbench/venv/bin:/home/trioka/bin:/home/trioka/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin'; mkdir -p /tmp/bench_mzbench_api_trioka-Vostro-2520_1562_828435_653902 && cd /tmp/bench_mzbench_api_trioka-Vostro-2520_1562_828435_653902 && rsync -aW  /home/trioka/cluster_test/mzbench/mzbench/workers/mqtt/ebin/ deployment_code && cd deployment_code/node && make generate_tgz && mv *.tgz /tmp/bench_mzbench_api_trioka-Vostro-2520_1562_828435_653831.tgz "
Exit code: 1
Output: bash: line 0: cd: deployment_code/node: No such file or directory

07:00:35.719 [error] [ API ] <0.479.0> Stage 'pipeline - provisioning': failed
Command returned 1:
 bash -c -l "export PATH='/home/trioka/cluster_test/mzbench/mzbench/venv/bin:/home/trioka/bin:/home/trioka/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin'; mkdir -p /tmp/bench_mzbench_api_trioka-Vostro-2520_1562_828435_653902 && cd /tmp/bench_mzbench_api_trioka-Vostro-2520_1562_828435_653902 && rsync -aW  /home/trioka/cluster_test/mzbench/mzbench/workers/mqtt/ebin/ deployment_code && cd deployment_code/node && make generate_tgz && mv *.tgz /tmp/bench_mzbench_api_trioka-Vostro-2520_1562_828435_653831.tgz "
Command output: bash: line 0: cd: deployment_code/node: No such file or directory

**Comment by parsifal-47** [comment]
Hi,
you adding new functions to the worker and no longer able to install it?
did you modified `make_install` command?

btw, you may also create an issue at https://github.com/mzbench/mzbench because this fork is more actively developed

Thanks!

**Comment by protostartup** [comment]
Hi, thanks for the quick reply. I got it working by using rsync  in the make_install.
