### ISSUE TITLE
No CLI after install with Erlang/OTP 20 and CentOs7

### ISSUE THREAD

**Issue by H3rby7** [satori-com/mzbench#157]
I tried to build a docker image for mzbench (see below)
I know there is a docker image available, but that uses another version of OTP which is incompatible with [vmq_mzbench](https://github.com/vernemq/vmq_mzbench).

I get a successfull install, but no "mzbench" binaries - in // find | grep mzb returns nothing alike. Any cluese?

```
FROM centos:7

RUN yum update -y && yum install -y wget git which make epel-release

RUN wget https://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm && rpm -Uvh erlang-solutions-1.0-1.noarch.rpm

ENV ERLANG_VER="20.0"
RUN wget https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_${ERLANG_VER}-1~centos~7_amd64.rpm && \
    yum install -y esl-erlang_${ERLANG_VER}-1~centos~7_amd64.rpm

ENV MZBENCH_VER="0.5.5"
RUN wget https://github.com/satori-com/mzbench/releases/download/${MZBENCH_VER}/mzbench-${MZBENCH_VER}-centos7.x86_64.rpm && \
    yum install -y mzbench-${MZBENCH_VER}-centos7.x86_64.rpm
```

**Comment by parsifal-47** [comment]
Hi,
please check this fork, it is a bit ahead with regards to OTP support:
https://github.com/mzbench/mzbench

**Comment by H3rby7** [comment]
So the idea is to use that fork and then build an .rpm from the sources there? (since there is no .rpm build for that tag)
Sorry if this questions seems weird, I am just not used to CentOS and Erlang

**Comment by H3rby7** [comment]
Okay I ended up doing:

git clone https://github.com/mzbench/mzbench
cd mzbench
docker build -t my-registry/myImage .
docker push my-registry/myImage

**Comment by parsifal-47** [comment]
oh, I got it, there is no binary `rpm` at `mzbench/mzbench`, this is not "by design", has to be fixed,
thanks for noticing!
