### ISSUE TITLE
ssh not found error in docker image

### ISSUE THREAD

**Issue by mdrobny** [satori-com/mzbench#160]
Hi

When I am using `mzbench` with `mzb_api_ec2_plugin` I got following error:

```
07:51:07.535 [error] [ API ] <0.1123.0> [ REMOTE EXEC ] Command execution failed: Cmd: ssh -A -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@10.1.70.135 "source /etc/profile; mkdir -p /tmp/mz/bench-0-1574581622" Exit code: 127 Output: sh: line 0: exec: ssh: not found
--
07:51:07.536 [error] [ API ] <0.994.0> Stage 'pipeline - provisioning': failed Command returned 127:  ssh -A -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@10.1.70.135 "source /etc/profile; mkdir -p /tmp/mz/bench-0-1574581622" Command output: sh: line 0: exec: ssh: not found
```

Somehow `ssh` is not part of `docker.io/ridrisov/mzbench:latest` image

Is the docker image broken? Why is it missing ssh?
I see it is installed here https://github.com/satori-com/mzbench/blob/master/Dockerfile#L12

**Comment by parsifal-47** [comment]
Hi,
yes, this doesn't look right,
we used `mzbench` inside ec2 on AMIs that are publicly available, list is here:
https://github.com/mzbench/mzbench/blob/master/doc/cloud_plugins.md#amazon-ec2

regardless of that, docker image has to have `ssh`, you are right,
the image from docker.io you referring to may be outdated, could you build and use one from here:
https://github.com/mzbench/mzbench

Thanks!

**Comment by mdrobny** [comment]
thanks for response

Yep I used proper AMI from the list but AMIs seem to be working fine. Only docker image is a problem I believe.
Wow I wasn't aware of https://github.com/mzbench/mzbench, it seems to be active repository!

Ok I will build docker image from https://github.com/mzbench/mzbench, push to my docker hub and I will try it in my k8s cluster

**Comment by mdrobny** [comment]
When building docker image from https://github.com/mzbench/mzbench I got following error :/

```
...

===> Compiling pretty_errors
===> Compiling mzbench_utils
===> Compiling _build/default/deps/mzbench_utils/src/mzb_lists.erl failed
_build/default/deps/mzbench_utils/src/mzb_lists.erl:37: illegal pattern
_build/default/deps/mzbench_utils/src/mzb_lists.erl:37: variable 'E' is unbound
_build/default/deps/mzbench_utils/src/mzb_lists.erl:37: variable 'ST' is unbound

make: *** [Makefile:87: .make/compilation-up-to-date] Error 1
make: Leaving directory '/opt/mzbench_src/server'
The command '/bin/sh -c mkdir -p ${HOME_DIR}/.local/share/mzbench_workers     && pip install -r requirements.txt     && make -C ./server generate     && cp -R ./server/_build/default/rel/mzbench_api ${MZBENCH_API_DIR}/     && make -C ./node install     && make -C ./node local_tgz     && ln -s ${HOME_DIR}/.local/cache/mzbench_api/packages/node-*_erts*.tgz ${HOME_DIR}/.local/cache/mzbench_api/packages/node-someversion-someos.tgz     && ln -s ${HOME_DIR}/.local/cache/mzbench_api/packages/node-*_erts*.tgz ${HOME_DIR}/.local/cache/mzbench_api/packages/node-$(git rev-parse HEAD)-someos.tgz' returned a non-zero code: 2
```

Those are final lines of docker build output.

Do I understand correctly that https://hub.docker.com/repository/docker/ridrisov/mzbench is the only existing docker image but it's not build from newest version of mzbench from https://github.com/mzbench/mzbench?

**Comment by parsifal-47** [comment]
yes, that is correct,
looks like Dockerfile from mzbench/mzbench is broken, that is interesting, could you open an issue there? (I mean in mzbench/mzbench) there are people who use it with k8s, they may comment on what is the status of this file

**Comment by mdrobny** [comment]
ok, will do, thanks :)

**Comment by mdrobny** [comment]
oh actually problem with docker build is already reported https://github.com/mzbench/mzbench/issues/15

**Comment by parsifal-47** [comment]
this is even funnier, it was me who forgot to follow-up, sorry
