### ISSUE TITLE
[Feature]: Handler for crashing of worker.

### ISSUE THREAD

**Issue by loguntsov** [satori-com/mzbench#88]
I didn't find any opportunity to track crash event of worker.
I would want track this event to make some actions. For example: decrease metric of current number of connections and increase faults counter.
Otherwise i can't track these crashes, and my metric has monotonically increases.

May we have other way to track these situations ?

**Comment by loguntsov** [comment]
Wow. Guys, i think you should make full revision of your documentation.
Because i found this:
https://github.com/machinezone/mzbench/blob/master/node/apps/mzbench/src/mzb_erl_worker.erl#L56

Think it is solution for my request. Am i right ?

**Comment by loguntsov** [comment]
But i can't find calls for this logic.

**Comment by parsifal-47** [comment]
We were not sure that this feature is usable and we have no examples currently,
you need to create `terminate_state` function at your worker module which accepts termination result and last worker state. Feel free to ask any questions.

Full documentation review is good idea, but I'm not sure that it could be done quick. Anyway, I put it to our internal task tracker

**Comment by loguntsov** [comment]
Ok. Thanks i will investigate this moment and will make patch for that. Think it is not very difficult.

**Comment by timofey-barmin** [comment]
PR was merged with some fixes. Feel free to reopen the issue if the current solution doesn't work for you.
